In [47]:
# ****************************************************************************************
#                            Task1 : Data Cleaning
# ****************************************************************************************

In [48]:
# ----------------------------------
#         Importing Libraries
# ----------------------------------

In [49]:
import pandas as pd

In [50]:
# ----------------------------------
#        Loading Dataset
# ----------------------------------

In [51]:
df = pd.read_csv(r"C:\Users\boyal\OneDrive\ElevateLabs_Internship\Task_01\01_Data\netflix_titles_raw_data.csv")

In [52]:
# ----------------------------------
#     understanding data set
# ----------------------------------

In [53]:
df.shape

(8807, 12)

In [54]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [55]:
# ----------------------------------
#      Checking Duplicates
# ----------------------------------

In [56]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [57]:
# ----------------------------------
#        Checking null values
# ----------------------------------

In [58]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [59]:
blank_values = (df["director"]=="").sum()
print(blank_values)

0

In [60]:
# ----------------------------------
#         Null handling
# ----------------------------------

In [61]:
df["director"].unique()

array(['Kirsten Johnson', nan, 'Julien Leclercq', ..., 'Majid Al Ansari',
       'Peter Hewitt', 'Mozez Singh'], dtype=object)

In [62]:
df["director"].nunique()

4528

In [63]:
df["director"] = df["director"].fillna("Unknown")

In [64]:
df["director"].isna().sum()

np.int64(0)

In [65]:
df["cast"].nunique()

7692

In [66]:
df["cast"] = df["cast"].fillna("Unknown")

In [67]:
df["cast"].isna().sum()

np.int64(0)

In [68]:
df['country'] = df['country'].fillna("Unknown")

In [69]:
df["country"].isna().sum()

np.int64(0)

In [70]:
df = df.dropna(subset="date_added")

In [71]:
df["date_added"].isna().sum()

np.int64(0)

In [72]:
df = df.dropna(subset="rating")

In [73]:
df["rating"].isna().sum()

np.int64(0)

In [74]:
df = df.dropna(subset="duration")
df["duration"].isna().sum()

np.int64(0)

In [75]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [76]:
# ----------------------------------
#    assinging proper data types
# ----------------------------------

In [77]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [78]:
cols = ["type", "director", "cast", "country", "rating", "listed_in", "description"]
df[cols] = df[cols].astype("string")

In [79]:
df["date_added"] = df["date_added"].str.strip()

In [80]:
df["date_added"] = pd.to_datetime(df["date_added"])

In [81]:
df["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

In [82]:
df.dtypes

show_id                 object
type            string[python]
title                   object
director        string[python]
cast            string[python]
country         string[python]
date_added      datetime64[ns]
release_year             int64
rating          string[python]
duration                object
listed_in       string[python]
description     string[python]
dtype: object

In [83]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [94]:
df.to_csv(
    r"C:\Users\boyal\OneDrive\ElevateLabs_Internship\Task_01\01_Data\netflix_cleaned_data.csv",
    index=False
)